# Generated by Django 5.0.1 on 2026-08-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
